services:
  fleuntd:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9880:9880"
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluentd.conf
    environment:
      - FLUENTD_CONF=fluentd.conf